package {

/** Automatically generated by the build. DO NOT EDIT. */
public class BuildConfig
{
    /** When the project was built. */
    public static const WHEN :String = "10:55:57 17/01/21";

    public static const DEBUG :Boolean = !false;

    public static const ANALYTICS_ID :String = "UA-1234567-1";

    public static const DATA_URL :String = "http://aduros.emufarmers.com/whirledbeat";
}

}
