package {

/** Automatically generated by the build. DO NOT EDIT. */
public class BuildConfig
{
    /** When the project was built. */
    public static const WHEN :String = "15:45:08 16/12/23";

    public static const DEBUG :Boolean = !false;

    public static const ANALYTICS_ID :String = "UA-1234567-1";
}

}
